# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 05:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(default='some text')),
                ('createdAt', models.DateTimeField(verbose_name=datetime.datetime(2018, 4, 12, 22, 0, 54, 573000))),
            ],
        ),
    ]
